# Step 1: Use an official lightweight Python image as the base
FROM python:3-slim
WORKDIR /usr/src/app
COPY requirements.txt ./
RUN python -m pip install --no-cache-dir -r requirements.txt
COPY app.py .
EXPOSE 5004
CMD ["python", "app.py"]
