version: "3.8"
services:
  match-service:
    build:
      context: .
      dockerfile: Dockerfile.match # Specify the custom Dockerfile
    volumes:
      - ./secrets:/app/secrets
    environment:
      - MATCH_DB_KEY=/app/secrets/Match_Key.json
    ports:
      - "5008:5008"
