version: "3.8"
services:
  match-service:
    build:
      context: .
      dockerfile: Dockerfile.match 
    volumes:
      - ./secrets:/app/secrets
    environment:
      - MATCH_DB_KEY=/app/secrets/Match_Key.json
    ports:
      - "5008:5008"
    networks:
      - grabOrgan-net

networks:
  grabOrgan-net:
    external: true