FROM python:3-slim

WORKDIR /usr/src/app

# Copy requirements and install dependencies
COPY requirements.txt ./
RUN python -m pip install --no-cache-dir -r requirements.txt

# Copy the service file
COPY composite/MatchOrgan/match_organ.py .

# # Copy the shared common folder from the repository root
# COPY common /usr/src/app/common

EXPOSE 5020

CMD ["python", "match_organ.py"]