services:
  pseudonym:
    build:
      context: ./
      dockerfile: Dockerfile.pseudonym
    image: GrabOrgan/pseudonym:1.0
    # restart: always
    container_name: pseudonym_service
    ports:
      - "5007:5007"
