services:
  delivery_info:
    build:
      context: ./
      dockerfile: Dockerfile.selectDriver
    image: GrabOrgan/deliveryinfo:1.0
    # restart: always
    container_name: selectDriver
    ports:
      - "5000:5000"