services:
  selectDriver:
    build:
      context: ./
      dockerfile: Dockerfile.selectDriver
    image: GrabOrgan/selectDriver:1.0
    # restart: always
    container_name: selectDriver
    ports:
      - "5024:5000"