# Dockerfile
FROM python:3.9-slim

WORKDIR /usr/src/app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY selectDriver.py .

# Expose the port the app runs on
EXPOSE 5024

# Command to run the application
CMD ["python", "selectDriver.py"]