version: "3.8"

services:
  organ:
    build:
      context: ./
      dockerfile: Dockerfile.organ
    image: graborgan/organ:1.0
    volumes:
      - ./secrets/organ_Key.json:/usr/src/app/secrets/organ_Key.json:ro
    environment:
      - ORGAN_DB_KEY=/usr/src/app/secrets/organ_Key.json
    ports:
      - "5009:5009"
    container_name: organ_service
    restart: always
