services:
  delivery_info:
    build:
      context: ./
      dockerfile: Dockerfile.trackDelivery
    image: GrabOrgan/deliveryinfo:1.0
    # restart: always
    container_name: trackDelivery
    ports:
      - "5002:5002"