services:
  trackDelivery:
    build:
      context: ./
      dockerfile: Dockerfile.trackDelivery
    image: GrabOrgan/trackDelivery:1.0
    # restart: always
    container_name: trackDelivery
    ports:
      - "5025:5002"