version: "3.8"

services:
  test-compatibility:
    build:
      context: .
      dockerfile: Dockerfile.testCompatibility
    container_name: "test-compatibility"
    #volumes map to secret key 
    environment:
      - RABBITMQ_HOST=common-rabbitmq-1
    networks:
      - grabOrgan-net
    ports:
      - "5022:5022"

networks:
  grabOrgan-net:
    external: true
