# Use official Python image
FROM python:3-slim

# Set working directory
WORKDIR /usr/src/app

# Copy dependency file and install
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy application files
COPY composite/TestCompatibility/test_compatibility.py ./test_compatibility.py

# Expose Flask port
EXPOSE 5022

# Run Flask app
CMD ["python", "test_compatibility.py"]
