# Use official Python image
FROM python:3.9

# Set working directory
WORKDIR /app

# Copy dependency file and install
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application files
COPY testCompatibility.py .

# Expose Flask port
EXPOSE 5022

# Run Flask app
CMD ["python", "testCompatibility.py"]
