# Dockerfile
FROM python:3-slim

WORKDIR /usr/src/app

# Install dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY createDelivery.py .

# Expose the port the app runs on
EXPOSE 5026

# Command to run the application
CMD ["python", "createDelivery.py"]